spring:
  application:
    name: question-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/QuestionsDB
      database: QuestionsDB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      mongodb:
        driver: DEBUG

server:
  port: 8086