spring:
  application:
    name: question-service
  data:
    mongodb:
      uri: mongo
      database: questionDB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8086