spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ai_answers
      database: ai_answers

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8087