spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ai_answers
      database: ai_answers
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: questions.exchange
  queue:
    name: questions.queue
  routing:
    key: questions.tracking

server:
  port: 8087