spring:
  application:
    name: userservice
  datasource:
    url: ${SPRING_DATA_URL}
    username: ${SPRING_DATA_USER}
    password: ${SPRING_DATA_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: ${SPRING_JPA_DIALECT}